In [1]:
import pandas as pd

In [2]:
data = {
    "product": ["Notebook", "Pen", "Backpack"],
    "price": [8.99, 1.25, 39.00],
    "units": [42, 130, 17]
}

data

{'product': ['Notebook', 'Pen', 'Backpack'],
 'price': [8.99, 1.25, 39.0],
 'units': [42, 130, 17]}

In [3]:
df = pd.DataFrame(data)

df

    product  price  units
0  Notebook   8.99     42
1       Pen   1.25    130
2  Backpack  39.00     17

In [4]:
from pathlib import Path

In [5]:
df = pd.read_csv(Path("..") / "data" / "raw" / "paperlane_orders.csv")

In [6]:
df.head()

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
3,1004,2026-01-06,Ava,East,Backpack,1,NaN,Returned
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete

In [7]:
# pd.read_csv("../data/raw/paperlane_orders.csv")

In [8]:
df.head(10)

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
3,1004,2026-01-06,Ava,East,Backpack,1,NaN,Returned
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,COMPLETE
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
7,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,NaN,Marker,4,2.50,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Complete

In [10]:
# .tail() to check the last rows
df.tail()

,order_id,order_date,customer,region,product,quantity,unit_price,status
5,1006,2026-01-07,Noah,West,Marker,3,2.50,COMPLETE
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
7,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,NaN,Marker,4,2.50,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Complete

In [11]:
# rows, columns
df.shape

(10, 8)

In [15]:
print(type(df.columns))

# .columns is a Pandas Index, can convert to a list with .tolist()
df.columns.tolist()

<class 'pandas.core.indexes.base.Index'>

['order_id',
 'order_date',
 'customer',
 'region',
 'product',
 'quantity',
 'unit_price',
 'status']

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    10 non-null     int64
 1   order_date  10 non-null     object
 2   customer    10 non-null     object
 3   region      9 non-null      object
 4   product     10 non-null     object
 5   quantity    10 non-null     int64
 6   unit_price  9 non-null      float64
 7   status      10 non-null     object
dtypes: float64(1), int64(2), object(5)
memory usage: 768.0+ bytes

In [19]:
df.describe()

         order_id   quantity  unit_price
count    10.00000  10.000000    9.000000
mean   1005.20000   3.200000   12.496667
std       2.65832   2.699794   15.389059
min    1001.00000   1.000000    1.250000
25%    1003.25000   2.000000    2.500000
50%    1005.50000   2.000000    8.990000
75%    1007.00000   3.750000    8.990000
max    1009.00000  10.000000   39.000000

In [22]:
# help(pd.DataFrame.describe)

In [20]:
df.describe(include='all')

,order_id,order_date,customer,region,product,quantity,unit_price,status
count,10.00000,10,10,9,10,10.000000,9.000000,10
unique,NaN,5,4,5,4,NaN,NaN,4
top,NaN,2026-01-08,Ava,Midwest,Notebook,NaN,NaN,Complete
freq,NaN,3,3,3,3,NaN,NaN,7
mean,1005.20000,NaN,NaN,NaN,NaN,3.200000,12.496667,NaN
std,2.65832,NaN,NaN,NaN,NaN,2.699794,15.389059,NaN
min,1001.00000,NaN,NaN,NaN,NaN,1.000000,1.250000,NaN
25%,1003.25000,NaN,NaN,NaN,NaN,2.000000,2.500000,NaN
50%,1005.50000,NaN,NaN,NaN,NaN,2.000000,8.990000,NaN
75%,1007.00000,NaN,NaN,NaN,NaN,3.750000,8.990000,NaN
max,1009.00000,NaN,NaN,NaN,NaN,10.000000,39.000000,NaN

In [25]:
int(True), int(False)

(1, 0)

In [26]:
df.isna().sum()

order_id      0
order_date    0
customer      0
region        1
product       0
quantity      0
unit_price    1
status        0
dtype: int64

In [30]:
# df['region'].value_counts().plot(kind='bar')

In [31]:
# df['unit_price'].plot(kind='hist')

In [34]:
df

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
3,1004,2026-01-06,Ava,East,Backpack,1,NaN,Returned
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,COMPLETE
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
7,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,NaN,Marker,4,2.50,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Complete

In [33]:
df.duplicated().sum()

1

In [35]:
# access the region column
# name_of_df['col_of_interest']
df['region']

0       East
1    Midwest
2       West
3       East
4      South
5       West
6    Midwest
7    Midwest
8        NaN
9      South
Name: region, dtype: object

In [36]:
df['region'].value_counts()

region
Midwest    3
East       2
South      2
 West      1
West       1
Name: count, dtype: int64

In [37]:
" West" == "West"

False

In [38]:
df['status'].value_counts()

status
Complete    7
complete    1
Returned    1
COMPLETE    1
Name: count, dtype: int64

In [39]:
# .value_counts(normalize=True) returns proportions
df['region'].value_counts(normalize=True)

region
Midwest    0.333333
East       0.222222
South      0.222222
 West      0.111111
West       0.111111
Name: proportion, dtype: float64

---

## Handling missing values and duplicates

In [41]:
df.drop_duplicates()

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
3,1004,2026-01-06,Ava,East,Backpack,1,NaN,Returned
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,COMPLETE
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,NaN,Marker,4,2.50,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Complete

In [42]:
print("Before: ", df.shape)

df = df.drop_duplicates()

print("After: ", df.shape)

Before:  (10, 8)
After:  (9, 8)

In [46]:
# df.reset_index()

Checking for missing values, strategies to deal with them

In [49]:
df.isna().sum()

order_id      0
order_date    0
customer      0
region        1
product       0
quantity      0
unit_price    1
status        0
dtype: int64

In [55]:
# first strategy is dropping missing values
# df.dropna() will drop any row where there's a missing value in any column

df = df.dropna(subset=['unit_price']) # only drop rows if there's a missing value in a specified col

In [56]:
df

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,COMPLETE
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,NaN,Marker,4,2.50,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Complete

In [59]:
# df['col'].fillna("value to replace missing values with")

df["region"] = df["region"].fillna("Unknown")

/var/folders/h2/tcglg5_x7flc_ly5fr_4fw5w0000gn/T/ipykernel_11454/902244736.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["region"] = df["region"].fillna("Unknown")

In [60]:
df

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,COMPLETE
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,Unknown,Marker,4,2.50,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Complete

In [62]:
# assuming we Hadn't dropped the row with the missing value in `unit_price`

df['unit_price'] = df['unit_price'].fillna(df['unit_price'].median())

/var/folders/h2/tcglg5_x7flc_ly5fr_4fw5w0000gn/T/ipykernel_11454/3255317642.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['unit_price'] = df['unit_price'].fillna(df['unit_price'].median())

In [63]:
df["region"].value_counts()

region
Midwest    2
South      2
East       1
 West      1
West       1
Unknown    1
Name: count, dtype: int64

In [64]:
df['region'] = df['region'].str.strip()

df['region'].value_counts()

/var/folders/h2/tcglg5_x7flc_ly5fr_4fw5w0000gn/T/ipykernel_11454/436662532.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['region'] = df['region'].str.strip()

region
Midwest    2
West       2
South      2
East       1
Unknown    1
Name: count, dtype: int64

In [65]:
df["status"].value_counts()

status
Complete    6
complete    1
COMPLETE    1
Name: count, dtype: int64

In [66]:
df["status"] = df["status"].str.strip().str.title()

df["status"].value_counts()

/var/folders/h2/tcglg5_x7flc_ly5fr_4fw5w0000gn/T/ipykernel_11454/3231388013.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["status"] = df["status"].str.strip().str.title()

status
Complete    8
Name: count, dtype: int64

In [ ]:
"string methods".title()

"can I make this all caps?".upper()

"CAN I MAKE THIS ALL LOWERCASE?!".lower()

"idk WhY this exists".swapcase()

In [75]:
df['order_date']

0    2026-01-05
1    2026-01-05
2    2026-01-06
4    2026-01-07
5    2026-01-07
6    2026-01-08
8    2026-01-08
9    01/09/2026
Name: order_date, dtype: object

In [85]:
df = df.head(7)

In [87]:
df['order_date'] = pd.to_datetime(df['order_date'])

df

/var/folders/h2/tcglg5_x7flc_ly5fr_4fw5w0000gn/T/ipykernel_11454/233908181.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['order_date'] = pd.to_datetime(df['order_date'])

,order_id,order_date,customer,region,product,quantity,unit_price,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,Complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,Complete
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete
8,1008,2026-01-08,Ava,Unknown,Marker,4,2.50,Complete

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 0 to 8
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    7 non-null      int64
 1   order_date  7 non-null      datetime64[ns]
 2   customer    7 non-null      object
 3   region      7 non-null      object
 4   product     7 non-null      object
 5   quantity    7 non-null      int64
 6   unit_price  7 non-null      float64
 7   status      7 non-null      object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 504.0+ bytes

In [89]:
# create a new column, df['name_of_new_col'] = value

df['order_month'] = df['order_date'].dt.month

/var/folders/h2/tcglg5_x7flc_ly5fr_4fw5w0000gn/T/ipykernel_11454/3289790612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['order_month'] = df['order_date'].dt.month

In [90]:
df

,order_id,order_date,customer,region,product,quantity,unit_price,status,order_month
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete,1
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,Complete,1
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete,1
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete,1
5,1006,2026-01-07,Noah,West,Marker,3,2.50,Complete,1
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete,1
8,1008,2026-01-08,Ava,Unknown,Marker,4,2.50,Complete,1

In [91]:
df['order_day_of_week'] = df['order_date'].dt.day_name()

/var/folders/h2/tcglg5_x7flc_ly5fr_4fw5w0000gn/T/ipykernel_11454/2065608.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['order_day_of_week'] = df['order_date'].dt.day_name()

In [92]:
df

,order_id,order_date,customer,region,product,quantity,unit_price,status,order_month,order_day_of_week
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete,1,Monday
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,Complete,1,Monday
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete,1,Tuesday
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete,1,Wednesday
5,1006,2026-01-07,Noah,West,Marker,3,2.50,Complete,1,Wednesday
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete,1,Thursday
8,1008,2026-01-08,Ava,Unknown,Marker,4,2.50,Complete,1,Thursday

In [94]:
df['revenue'] = df['quantity'] * df['unit_price']

df

/var/folders/h2/tcglg5_x7flc_ly5fr_4fw5w0000gn/T/ipykernel_11454/1529980868.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['revenue'] = df['quantity'] * df['unit_price']

,order_id,order_date,customer,region,product,quantity,unit_price,status,order_month,order_day_of_week,revenue
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete,1,Monday,17.98
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,Complete,1,Monday,12.50
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete,1,Tuesday,8.99
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete,1,Wednesday,6.25
5,1006,2026-01-07,Noah,West,Marker,3,2.50,Complete,1,Wednesday,7.50
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete,1,Thursday,78.00
8,1008,2026-01-08,Ava,Unknown,Marker,4,2.50,Complete,1,Thursday,10.00

In [95]:
# to access multiple columns, df[['list', 'of', 'cols']]

df[['product', 'quantity', 'unit_price', 'revenue']]

    product  quantity  unit_price  revenue
0  Notebook         2        8.99    17.98
1       Pen        10        1.25    12.50
2  Notebook         1        8.99     8.99
4       Pen         5        1.25     6.25
5    Marker         3        2.50     7.50
6  Backpack         2       39.00    78.00
8    Marker         4        2.50    10.00

In [96]:
# to filter our dataset, df[df['col'] == 'some_condition']
df[df['quantity'] >= 5]

,order_id,order_date,customer,region,product,quantity,unit_price,status,order_month,order_day_of_week,revenue
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,Complete,1,Monday,12.50
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete,1,Wednesday,6.25

In [97]:
df[df['region'] == 'Midwest']

,order_id,order_date,customer,region,product,quantity,unit_price,status,order_month,order_day_of_week,revenue
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,Complete,1,Monday,12.5
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete,1,Thursday,78.0

In [98]:
# filter on multiple conditions
# df[(condition_1) & (condition_2)]

df[(df['region'] == 'Midwest') & (df['quantity'] > 2)]

,order_id,order_date,customer,region,product,quantity,unit_price,status,order_month,order_day_of_week,revenue
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,Complete,1,Monday,12.5

In [99]:
# store our filtered dataframe in a new variable

df_complete = df[df['status'] == 'Complete'].copy() # .copy() creates an independent copy

Save `df_complete` to our `processed` folder

In [100]:
df_complete

,order_id,order_date,customer,region,product,quantity,unit_price,status,order_month,order_day_of_week,revenue
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Complete,1,Monday,17.98
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,Complete,1,Monday,12.50
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Complete,1,Tuesday,8.99
4,1005,2026-01-07,Priya,South,Pen,5,1.25,Complete,1,Wednesday,6.25
5,1006,2026-01-07,Noah,West,Marker,3,2.50,Complete,1,Wednesday,7.50
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Complete,1,Thursday,78.00
8,1008,2026-01-08,Ava,Unknown,Marker,4,2.50,Complete,1,Thursday,10.00

In [101]:
# .to_csv("file_path/to/file/new_filename.csv", index=False) so index isn't exported
df_complete.to_csv(Path("..") / "data" / "processed" / "paperlane_orders_clean.csv", index=False)

in `.to_csv()` typically you'll set `index=False` unless you care about the index. 

If it's a simple `RangeIndex`, you don't need to export it.

In [102]:
df_complete.to_csv(Path("..") / "data" / "processed" / "paperlane_orders_clean_index.csv")